# Generated by Django 4.1 on 2022-08-30 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=30, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
    ]
