# Generated by Django 4.1 on 2022-08-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='account_active',
            field=models.BooleanField(default=False),
        ),
    ]
