# Generated by Django 4.1 on 2022-08-30 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_app_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 16, 17, 4, 25177, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='app_user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
