# Generated by Django 4.1 on 2022-08-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_logs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='country',
            field=models.CharField(blank=True, default='Anonymous User', max_length=255),
        ),
    ]
